### ISSUE TITLE
User is able to register new user with same email and different password

### ISSUE THREAD

**Issue by artur-gajewski** [sne11ius/play-silhouette-slick-seed#9]
When user register an account and then logs out, he/she is able to register again with same email address and different password and then gets automatically logged in. The password of the user gets updated.

Problem:

If I know someone's email address, I can change his/her firstname, lastname and password by registering that email address again.

Steps to recreate:

1. Register user
2. Logout
3. Register another user with different first name, last name and password
4. Logout
5. Try to login with first user credentials -> unable
6. Try to login with the latest password -> success

**Comment by sne11ius** [comment]
Yes, you are right, thanks for the info.
But please note that this project is a fork of the original 1.0 silhouette slick seed demo, where the same behaviour can be observed.
The behaviour is fixed in the current silhouette seed, have a look at how it was done: https://github.com/mohiva/play-silhouette-seed/blob/master/app%2Fcontrollers%2FSignUpController.scala#L48

It wouldn't be too hard to fix this in this slick-version of the seed. However... I won't.
I'm planning to resync this project to the original silhouette seed once a final 2.0 version of it is released.

I hope you understand this.

**Comment by artur-gajewski** [comment]
Hello and thanks for the response. Do you have any idea when the version
2.0 will be released?

Yours,

Artur

2015-02-11 20:43 GMT+02:00 Cornelius Lilge <notifications@github.com>:

> Yes, you are right, thanks for the info.
> But please note that this project is a fork of the original 1.0 silhouette
> slick seed demo, where the same behaviour can be observed.
> The behaviour is fixed in the current silhouette seed, have a look at how
> it was done:
> https://github.com/mohiva/play-silhouette-seed/blob/master/app%2Fcontrollers%2FSignUpController.scala#L48
>
> It wouldn't be too hard to fix this in this slick-version of the seed.
> However... I won't.
> I'm planning to resync this project to the original silhouette seed once a
> final 2.0 version of it is released.
>
> I hope you understand this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sne11ius/play-silhouette-slick-seed/issues/9#issuecomment-73938204>
> .
>



-- 
Ystävällisin terveisin / Kind regards,

Artur Gajewski

**Comment by sne11ius** [comment]
Seems to be scheduled for end of the week. Have a look here.
https://github.com/mohiva/play-silhouette-seed/issues/32#issuecomment-73958726
I'm not sure when I will find the time to make a new slick version though...

**Comment by artur-gajewski** [comment]
Hello,

Any idea when you will be able to sync the Slick seed with the silhouette
2.0? I would be in need of your seed but if it will take some time perhaps
I could try to make it myself. Although I'm still a noob with Scala so I
might end up with a mess :D

Yours,

Artur

2015-02-12 18:05 GMT+02:00 Cornelius Lilge <notifications@github.com>:

> Seems to be scheduled for end of the week. Have a look here.
> mohiva#32 (comment)
> <https://github.com/mohiva/play-silhouette-seed/issues/32#issuecomment-73958726>
> I'm not sure when I will find the time to make a new slick version
> though...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sne11ius/play-silhouette-slick-seed/issues/9#issuecomment-74096939>
> .
>



-- 
Ystävällisin terveisin / Kind regards,

Artur Gajewski

**Comment by sbrunk** [comment]
I've already merged the changes for 2.0 from the original silhouette seed back into the slick seed. Works fine for me so far.
Available here: https://github.com/sbrunk/play-silhouette-slick-seed
